### ISSUE TITLE
Shared volume for multiple Trivy instances

### ISSUE THREAD

**Issue by holyhope** [aquasecurity/harbor-scanner-trivy#135]
Hello,

At OVH we plan to deploy Trivy for our [Managed private reigstry service](https://www.ovhcloud.com/en/public-cloud/managed-private-registry/) based on [Harbor](https://goharbor.io).

**Context** I would like to deploy Trivy for hundreds of customers.
**Environment** Harbor on Kubernetes clusters thanks to [Harbor Operator](https://github.com/goharbor/harbor-operator).

1. Is it ok to deploy **multiple Trivy* (HA) with a **shared volume** for `/home/scanner/.cache` for a **single customer**?
1. What kind of data are stored in `/home/scanner/.cache`? Is there *personal* data?
   Is it possible to share single Trivy instance with multiple harbor?
   Or probably safer, distinct Trivy but with a shared `/home/scanner/.cache` directory?
   Or even safer, distinct Trivy but with a shared `/home/scanner/.cache/trivy/db/trivy.db` file?

Any help appreciated.
Cheers

**Comment by danielpacak** [comment]
Hi @holyhope . Please find my answers below:

> 1. Is it ok to deploy trivy adapter service (HA) with a shared volume for /home/scanner/.cache?

Nope. Behind the scenes the adapter service runs `trivy` executable binary. However the `trivy` binary does not expect that multiple Trivy processes update the same `trivy.db` file at the same time. Sharing the /home/scanner/.cache volume might causes the inconsistent state of the DB file.

> 2. What kind of data are stored in /home/scanner/.cache? Is there personal data?

1. `/home/scanner/.cache/reports` - temporary vulnerability report files in JSON format (`trivy --format json`); programmatically deleted by the adapter service on scan completion
2. `/home/scanner/.cache/trivy/db/trivy.db` - vulnerabilities DB / index downloaded from GitHub https://github.com/aquasecurity/trivy-db/releases
3. `/home/scanner/.cache/trivy/db/metadata.json` - mata data descriptor of `trivy.db` file
4. `/home/scanner/.cache/trivy/fanal/fanal.db` - cache of partial vulnerability reports index by image layer

Since we only store vulnerability data, the cache would not hold personal data even if a scanned image contained such data.

> 3. Is it possible to share single Trivy instance with multiple harbor?

Technically it is possible, but in HA setup such instance will receive and enqueue lots of scan requests, which are processed asynchronously.

To sum up, as explained in 1. sharing `trivy.db` is tempting but not recommended. That was a reason why [our Helm chart](https://github.com/aquasecurity/harbor-scanner-trivy/blob/master/helm/harbor-scanner-trivy/templates/statefulset.yaml#L15) and the official [Harbor Helm chart](https://github.com/goharbor/harbor-helm/blob/master/templates/trivy/trivy-sts.yaml#L165) deploys the adapter service as a StatefulSet to take advantage of persistent volume claim template.

**Comment by holyhope** [comment]
Hello @danielpacak ,

Thank you a lot for this full response! 😊
Sadly it means that I cannot share Trivy instances the way I imagined.
So I think that we will start with a dedicated Trivy deployment per Harbor.

This is the configuration I will recommend in the [Harbor Operator](https://github.com/goharbor/harbor-operator).

**Comment by holyhope** [comment]
I closed it in a hurry, but I still have a question :

> Nope. Behind the scenes the adapter service runs trivy executable binary1. However the trivy binary does not expect that multiple Trivy processes update the same trivy.db file at the same time. Sharing the /home/scanner/.cache volume might causes the inconsistent state of the DB file.

I was talking about Trivy with database update disabled (a single distinct Trivy instance will update `trivy.db` from an other side). So, if I am right, there will be no concurrent write in `trivy.db`?
Or maybe Trivy still write in (and lock) `trivy.db` during scan operations?

Let me summarise:
Single Trivy which download trivy.db from Github. Multiple Trivy instances which use the `trivy.db` for scans.

Does it seems coherent in your opinion? 😊

**Comment by danielpacak** [comment]
Hey @holyhope If I understand you correctly you'd still want to share the `trivy.db` as follows

![harbor-scanner-trivy-ha](https://user-images.githubusercontent.com/1322923/90250614-9d7f6f80-de3c-11ea-8d26-8b7da79534f5.png)

For me it's still not feasible as we also have `fanal.db`, which is updated by each trivy process. What's more I believe that trivy is using BoltDB / memory mapped file, which cannot be read concurrently by multiple processes. Is that correct @knqyf263 ?

**Comment by holyhope** [comment]
Yes that is what I imagined for `trivy.db`.
But you think that this does not work? Cause of BoltDB and concurrent read?
Seems strange, even if Trivy map the db in memory, I do not see why there will be concurrent issue. I would love to hear @knqyf263 about that 😊

About `fanal.db` I got it that it should not be shared due to concurrent writes.👌

**Comment by knqyf263** [comment]
BoltDB doesn't allow multiple processes to open the same database. 

>Please note that Bolt obtains a file lock on the data file so multiple processes cannot open the same database at the same time. Opening an already open Bolt database will cause it to hang until the other process closes it. To prevent an indefinite wait you can pass a timeout option to the Open() function:

https://github.com/etcd-io/bbolt/blob/master/README.md#opening-a-database

We may be able to use `Read-Only Mode`, but it blocks any processes from opening the database in read-write mode.

>Sometimes it is useful to create a shared, read-only Bolt database. To this, set the Options.ReadOnly flag when opening your database. Read-only mode uses a shared lock to allow multiple processes to read from the database but it will block any processes from opening the database in read-write mode.

https://github.com/etcd-io/bbolt/blob/master/README.md#read-only-mode

So, if Trivy process scanning the image opens the database in read-only mode, another process updating the database cannot open it in read-write mode.

BTW, technically speaking, `fanal.db` contains the image information only such as OS, package, and library name/version, not vulnerability.
>/home/scanner/.cache/trivy/fanal/fanal.db - cache of partial vulnerability reports index by image layer

**Comment by danielpacak** [comment]
@holyhope Can we close this one as answered?
