### ISSUE TITLE
Slow Scanner Performance

### ISSUE THREAD

**Issue by sidewinder12s** [aquasecurity/harbor-scanner-trivy#168]
Hello, 

We're running into slow scanning performance with scans regularly taking 20 minutes to finish on pushed images. 

We're using the latest version of the harbor-helm chart for deployment to EKS.

The jobservice does not appear to be overwhelmed & the trivy container seems to max out at around 1 vCPU of usage in an EKS cluster, even with limits raised. 

We do have a lot of traffic coming into Harbor with a lot of 2-3GB images pushed regularly.

I am wondering, what is the recommended methods to increase scanner throughput?

- Increase Resources? (didn't seem to impact resource usage or throughput)
- Increase Trivy replica count?
- Increase `SCANNER_JOB_QUEUE_WORKER_CONCURRENCY`?

My read of the architecture doc is that option 2 should be fine and that it should only increase load on the in chart redis container (which doesn't appear very throttled currently).

Thanks!

**Comment by danielpacak** [comment]
Hi @sidewinder12s I'd recommend trying out option two as well, i.e. scale up the adapter service.

The `SCANNER_JOB_QUEUE_WORKER_CONCURRENCY` env parma is a bit unfortunate and should be set at 1. We're going to deprecate and eventually remove it. Long story short, this is because in Trivy Standalone mode multiple Trivy processes cannot share the same Trivy DB file.

**Comment by danielpacak** [comment]
Closing as answered. Please reopen or create another issue if you still have questions related to performance and scale.
