### ISSUE TITLE
How overall artifact vulnerability severity is calculated and displayed in Harbor UI?

### ISSUE THREAD

**Issue by piyush94** [aquasecurity/harbor-scanner-trivy#171]
I have a query. How is the overall artifact vulnerability severity is calculated?
For example, the below artifact doesn't have any critical vulnerability but overall severity is listed as Critical in Harbor.

![image](https://user-images.githubusercontent.com/11614204/123208465-c355b600-d4dc-11eb-8884-480a8ab78d80.png)

Thanks.

**Comment by danielpacak** [comment]
For each vulnerability this adapter service maps severities used by Trivy to severities defined by Harbor Pluggable Scanners API v1.1:

| Trivy | Harbor |
|---|---|
| CRITICAL | Critical |
| HIGH | High |
| MEDIUM | Medium |
| LOW | Low |
| UNKNOWN | Unknown |

Then it calculates the highest severity in the loop. According to the [`toHighestSeverity`](https://github.com/aquasecurity/harbor-scanner-trivy/blob/v0.19.0/pkg/scan/transformer.go#L147) method and your example the highest severity should be **High** instead of Critical.

Could you specify which version of Harbor are you using? I believe that we should check Harbor Core and Harbor UI code how they handle overall severity returned by a scanner adapter. I check this Trivy adapter service and things look okey.

**Comment by piyush94** [comment]
We are using Harbor v2.2.1.

**Comment by danielpacak** [comment]
Okey so this might be related to https://github.com/goharbor/harbor/issues/14929

**Comment by piyush94** [comment]
Ok, please go ahead and close this issue if the fix is needed in Harbor.

**Comment by danielpacak** [comment]
Closing as duplicate of https://github.com/goharbor/harbor/issues/14929.
