### ISSUE TITLE
inconsistency in the report generated

### ISSUE THREAD

**Issue by piyush94** [aquasecurity/harbor-scanner-trivy#211]
**What steps did you take and what happened:**

When scanning an image multiple times, there is inconsistency in the report generated.

**What did you expect to happen:**

Vulnerability report should not change with each consecutive scan.

**Anything else you would like to add:**

I am running the Harbor Scanner Adapter for Trivy in K8s using the official Helm chart. I've set the `replicaCount `to 3. The scanner is exposed using ingress.

Is there is a sync between the 3 pods ? Does having 3 pods can cause the above issue?

**Update:** I am NOT facing the issue with a single pod.

[Miscellaneous information that will assist in solving the issue.]

I have API and Trivy debug set to true. I see a lot of `Analysis error: unable to parse` errors, which are not there when running standalone Trivy in debug mode. Are these the adapter logs ?

**Environment:**

- Harbor version: v2.2.1-b0d63082
- Harbor Scanner Adapter for Trivy version: 0.21.0
- Harbor installation process: Installer script `install.sh --with-chartmuseum`

**Comment by danielpacak** [comment]
👋 @piyush94  Thank you for reporting this issue. We've seen a similar behaviour and it was fixed in Harbor 2.4. See https://github.com/goharbor/harbor/issues/15623 and https://github.com/goharbor/harbor/issues/16052 for more details.

Having multiple instances of Trivy scanner pod should not be the issue so long Harbor core is updating vulnerability records in a transaction. Do let us know if the problem with multiple pods persists in Harbor 2.4.

**Comment by piyush94** [comment]
@danielpacak Thanks for the info. I tried in Harbor 2.4.0 and issue seems to be fixed.
By any chance this fix will be backported to 2.3.x ?

**Comment by danielpacak** [comment]
> @danielpacak Thanks for the info. I tried in Harbor 2.4.0 with multiple pods and issue seems to be fixed.
> By any chance this fix will be backported to 2.3.x ?

I'm not aware of any plans for backporting fixes to 2.3.x, but the best would be to ask Harbor maintainers, who are responsible for releases, in the Slack channel.
