### ISSUE TITLE
How do I run without docker?

### ISSUE THREAD

**Issue by zhuxindong** [aquasecurity/harbor-scanner-trivy#235]
How do I run without docker ? 
Can I just  run  it use binary file? how do i specify parameters？

**Comment by danielpacak** [comment]
You can just download executable binary and run it as any other program:

```console
$ wget https://github.com/aquasecurity/harbor-scanner-trivy/releases/download/v0.28.0/harbor-scanner-trivy_0.28.0_Linux_x86_64.tar.gz
$ tar -xvf harbor-scanner-trivy_0.28.0_Linux_x86_64.tar.gz
$ ./scanner-trivy
{"built_at":"2022-04-21T10:02:51Z","commit":"e0160bc153644fa65eef9c5c0dd91417d1eb18d0","level":"info","msg":"Starting harbor-scanner-trivy","time":"2022-04-28T08:11:49Z","version":"0.28.0"}
{"level":"warning","msg":"trivy cache dir does not exist","path":"/home/scanner/.cache/trivy","time":"2022-04-28T08:11:49Z"}
{"level":"fatal","msg":"Error: checking config: creating trivy cache dir: mkdir /home/scanner: permission denied","time":"2022-04-28T08:11:49Z"}
```

Most likely, you'll see a similar error as in the output above, because there is a bunch of environment variables that must be set in order to configure the adapter service.

Check Helm templates for example https://github.com/aquasecurity/harbor-scanner-trivy/blob/main/helm/harbor-scanner-trivy/templates/statefulset.yaml#L45 and [Configuration](https://github.com/aquasecurity/harbor-scanner-trivy#configuration) reference.
