### ISSUE TITLE
New scanner version (v0.30.0) consumes too much CPU

### ISSUE THREAD

**Issue by hasonhai** [aquasecurity/harbor-scanner-trivy#255]
**What steps did you take and what happened:**

We install the new scanner version v0.30.0 and do a full scan in our Harbor with around 8200 images.
The old version (v0.27.0) took 2.5 hours to finish. CPU used is little. I have 3 instances of it and each only consume 0.25 core in average.
The new version (v0.30.0) took 6 hours and just finished 1200 images. CPU used is quite high. I have 3 instances of its and each consume full 2 cores. 
Both of the version were deployed with the same settings and works with the same Harbor registry.

CPU usage of v0.27.0
![imgpsh_mobile_save](https://user-images.githubusercontent.com/1762517/181641783-094736cc-6d34-4660-a76e-a6ac1e2084b7.jpg)

CPU usage of v0.30.0
![imgpsh_mobile_save](https://user-images.githubusercontent.com/1762517/181641819-faf6ee13-f8ad-47a3-bb30-d44887cbfad1.jpg)

Memory usage of them are similar and low.
Network throughput is also not stand out.

**What did you expect to happen:**

I expected that the CPU consumption difference does not have this large gap. 

**Environment:**

- Harbor version: v2.4.1
- Harbor Scanner Adapter for Trivy version: v0.30.0
- Harbor installation process: harbor-helm

**Comment by lixdavid94** [comment]
@hasonhai I noticed the same behavior with the trivy scans taking longer. I think it's because of [secret scanning](https://aquasecurity.github.io/trivy/v0.27.0/docs/secret/scanning/) which was introduced in trivy `v.027.0`. I've since rolled back to adapter version `v.0.28.0` which used trivy `v.0.26.0` that doesn't have the secret scanning feature.

I have this [issue](https://github.com/aquasecurity/harbor-scanner-trivy/issues/252) opened to see if there is a way to disable secret scanning.
